# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd = {
    luks.devices."cryptroot" = {
      device = "/dev/disk/by-uuid/715ec013-991d-4794-a940-6dfbceb939b6";
      preLVM = true;
      allowDiscards = true;
    };
  };
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a9e5f999-77a7-4bbe-86fa-771bddc3a2ca";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EEC0-15FC";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f7a2441f-a4e2-4d9f-83ae-032fea2a701f"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
