# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  # boot.kernelPackages = pkgs.linuxPackagesFor pkgs.linux_latest;# boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "kvm-intel" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.blacklistedKernelModules = [ "modesetting" "snd_hda_intel" ];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = ''
    options snd_hda_intel enable=1,6
  '';

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/13450889-c539-4b40-a46d-7948bca33315";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DEE7-3C5C";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/9a9cec39-b1e0-4d96-a1ca-0e197e42ea15"; }];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
