# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath, config, lib, pkgs, ... }:

{
  imports =
    [
      ("${modulesPath}/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" "r8169" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];


  boot.loader.grub.device = "nodev"; # or "nodev" for efi only
  boot.initrd = {
    luks.devices = {
      "m2crypt" = {
        device = "/dev/disk/by-uuid/ceb75a70-c7d8-44a5-b91f-9cdd75d415e7";
        preLVM = true;
        allowDiscards = true;
      };
      "satacrypt" = {
        device = "/dev/disk/by-uuid/d089dd88-be21-45ea-a1e9-21958368359a";
        preLVM = true;
        allowDiscards = true;
      };
      "cryptsata2" = {
        device = "/dev/disk/by-uuid/45f0e79b-bbfc-4a7d-9686-b1604f792b10";
        preLVM = true;
        allowDiscards = true;
      };
    };
  };
  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/cc80867a-3ae2-464c-89a9-243503324c0a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/4D37-459A";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/ab56ff99-9bc0-4d6b-9a50-44cb66122c1e"; }];

  nix.settings.max-jobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };

  services.xserver.videoDrivers = ["nvidia"];

  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    powerManagement.finegrained = false;
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
    prime = {
      sync.enable = true;

      intelBusId = "PCI:0:2:0";
      nvidiaBusId = "PCI:1:0:0";
    };
  };

}
