# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot = {
    initrd = { availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" ]; kernelModules = [ ]; };
    loader = { systemd-boot.enable = true; efi.canTouchEfiVariables = true; };
    kernelModules = [ "kvm-amd" ];
    kernelParams = [ "console=ttyS0" "console=tty1" "nvme.shutdown_timeout=10" "libiscsi.debug_libiscsi_eh=1" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = { device = "/dev/disk/by-uuid/19d58aea-de68-4cec-844f-3e8e6a0a5669"; fsType = "ext4"; };
    "/boot" = { device = "/dev/disk/by-uuid/093C-1727"; fsType = "vfat"; };
  };

  swapDevices = [{ device = "/swapfile"; priority = 0; }];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
